#!/bin/bash
subject=$(shuf -n 1 subject)
paragraph1=$(shuf -n 1 phrases)
paragraph2=$(shuf -n 3 phrases  |tr -d '\n')
paragraph3=$(shuf -n 1 subject)
from=$(shuf -n 1 email)

{
echo "From: $from"
echo "To: General Queue <queue@iu.edu>"
echo "Subject: $subject"
echo
echo
echo "Hello,"
echo "$paragraph1"
echo
echo "$paragraph2"
echo
echo "$paragraph3,"
echo $from|awk '{print $1}'
} | podman exec -i rt rt-mailgate --url http://localhost:8080 --queue general --action correspond